name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main   # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # match your project

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Zip build folder
        run: |
          cd build
          zip -r ../build.zip .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # replace with your EB region

      - name: Upload & Deploy to Elastic Beanstalk
        run: |
          APP_NAME="my-ecom-app"          # <-- replace with your EB Application name
          ENV_NAME="my-ecom-app-env"      # <-- replace with your EB Environment name
          DEPLOY_BUCKET="my-ecom-app-deployments"  # <-- create this S3 bucket manually in same region

          VERSION_LABEL="build-${GITHUB_SHA}"

          # Upload artifact to S3
          aws s3 cp build.zip s3://$DEPLOY_BUCKET/$VERSION_LABEL.zip --region us-east-1

          # Register new app version
          aws elasticbeanstalk create-application-version \
            --application-name $APP_NAME \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket=$DEPLOY_BUCKET,S3Key=$VERSION_LABEL.zip

          # Deploy to environment
          aws elasticbeanstalk update-environment \
            --environment-name $ENV_NAME \
            --version-label $VERSION_LABEL